services:
  mariadb-keycloak:
    image: mariadb:10.6
    container_name: mariadb-keycloak
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${KEYCLOAK_MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${KEYCLOAK_DB_NAME}
      - MYSQL_USER=${KEYCLOAK_DB_USER}
      - MYSQL_PASSWORD=${KEYCLOAK_DB_PASSWORD}
    volumes:
      - mariadb-keycloak-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - keycloak-net

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: keycloak
    restart: unless-stopped
    extra_hosts:
      - "keycloak.local:192.168.56.103"
      - "wordpress.local:192.168.56.103"
    depends_on:
      mariadb-keycloak:
        condition: service_healthy
    volumes:
      - /var/log/containers/keycloak:/opt/keycloak/data/log
    environment:
      - KC_DB=mariadb
      - KC_DB_URL=jdbc:mariadb://mariadb-keycloak:3306/${KEYCLOAK_DB_NAME}
      - KC_DB_USERNAME=${KEYCLOAK_DB_USER}
      - KC_DB_PASSWORD=${KEYCLOAK_DB_PASSWORD}
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN_USER}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KC_HOSTNAME=${KEYCLOAK_DOMAIN}
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_HTTP_ENABLED=true
      - KC_PROXY=edge
    command: start
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak.rule=Host(`${KEYCLOAK_DOMAIN}`)"
      - "traefik.http.routers.keycloak.tls=true"
      - "traefik.http.services.keycloak.loadbalancer.server.port=8080"
      - "traefik.docker.network=traefik-net"
    networks:
      - keycloak-net
      - traefik-net

volumes:
  mariadb-keycloak-data:

networks:
  traefik-net:
    external: true
  keycloak-net:
    name: keycloak-net
    driver: bridge